pretrained_model_path: "/path/to/DynaMind-main/outputs/DGVR/checkpoints/stable-diffusion-v1-4"
output_dir: "/path/to/DynaMind-main/outputs/DGVR/checkpoints/tuned/1"

train_data:
  video:
  prompt: "a panda is eatting bamboo"
  n_sample_frames: 6
  width: 512
  height: 288
  sample_start_idx: 0
  sample_frame_rate: 8

validation_data:
  prompts:
    - "a cat is sitting on the ground"
    - "an airplane in the sky"
    - "a person is dancing"
  video_length: 6
  width: 512
  height: 288
  num_inference_steps: 48
  guidance_scale: 12.2
  use_inv_latent: False
  num_inv_steps: 48

learning_rate: 9.5e-6
train_batch_size: 1
max_train_steps: 520
checkpointing_steps: 960
validation_steps: 96
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 37
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
