train:
  batch_size: 30
  learning_rate: 0.000028
  num_epochs: 192
  alignment_loss_weight: 0.022

dataset:
  eeg_path: "/path/to/DynaMind-main/data/EEG_processed/sub1.npy"
  vae_path: "/path/to/DynaMind-main/data/vae_latents/latents.pt"
  in_channels: 64
  total_time_len: 4000
  num_video_frames: 33

model:
  filter_num_filters: 2
  patch_embed_dim: 512
  conv_out_channels: 1024
  patch_length: 800
  patch_stride: 100

projection:
  vae_latent_c: 8
  vae_latent_h: 60
  vae_latent_w: 90
  clip_emb_dim: 768
