# config.yaml

# 训练配置
train:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 200
  alignment_loss_weight: 0.01
  consistency_loss_weight: 0.99

# 数据集配置
dataset:
  groups: 7
  classes: 40
  samples_per_class: 5
  in_channels: 62
  total_time_len: 400
  num_video_frames: 6

# 模型配置
model:
  filter_num_filters: 4
  patch_embed_dim: 256
  conv_out_channels: 512
  # 滑动窗口参数
  patch_length: 100 # 每个切片的长度，建议是 total_time_len / num_video_frames 附近
  patch_stride: 60 # 每次滑动的步长，小于 patch_length 会产生重叠

# 投影目标维度配置
projection:
  vae_latent_c: 4
  vae_latent_h: 36
  vae_latent_w: 64
  clip_emb_dim: 768